### ISSUE TITLE
Any way to install/execute on Windows without VC++ 9.0?

### ISSUE THREAD

**Issue by glenviewjeff** [rllynch/smartthings_cli#2]
When executing the setup.py install command on Windows Python 2.7, the script fails showing a requirement to install Visual C++ 9.0.  Is there any other way around this?

http://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat

**Comment by rllynch** [comment]
The VC++ 9.0 requirement is coming from the version of Python you installed and is unrelated to smartthings_cli.  I'd recommend following the advice on that Stackoverflow post.
