### ISSUE TITLE
Prompt for API domain URL

### ISSUE THREAD

**Issue by feakk** [rllynch/smartthings_cli#4]
Thanks for the awesome code. For your initial innovation/initialization command, can you add an optional --api_url (or equivalent) to account for differences in which Samsung site binds the API and store that for all future queries? I have to access graph-na02-useast1.api.smartthings.com for API calls as graph.api.smartthings.com is blank.

Example:
$ smartthings_cli --clientid CLIENTID --clientsecret CLIENTSECRET --api_url graph-na02-useast1.api.smartthings.com

Rationale:
$ smartthings_cli query switch all
Traceback (most recent call last):
  File "c:\programdata\anaconda2\scripts\smartthings_cli-script.py", line 11, in <module>
    load_entry_point('smartthings-cli==1.0', 'console_scripts', 'smartthings_cli')()
  File "build\bdist.win-amd64\egg\smartthings_cli\smartthings_cli.py", line 305, in main
  File "build\bdist.win-amd64\egg\smartthings_cli\smartthings_cli.py", line 128, in get_status
TypeError: string indices must be integers

# Replacing all URL references in the source resolves the issue:
$ sed -i 's#graph.api.smartthings.com#graph-na02-useast1.api.smartthings.com#' build\bdist.win-amd64\egg\smartthings_cli\smartthings_cli.py
$ smartthings_cli query switch all
2017-11-11 12:55:44,256 INFO     switch Light Example: True
...

Regards,
Paul

**Comment by rllynch** [comment]
This is fixed in a955f48f814dedfd0d77d3a42efe7c920087776a
